export { NavBarComponent } from './nav-bar/nav-bar.component';
export { BwsButtonComponent } from './bws-button/bws-button.component';
export { CtaCardComponent } from './cta-card/cta-card.component';
export { EstudioSectionComponent } from './estudio-section/estudio-section.component';
export { FreeJefrySectionComponent } from './freejefry-section/freejefry-section.component';
export { FjCardDeckComponent } from './fj-card-deck/fj-card-deck.component';
export { DesarrolloSectionComponent } from './desarrollo-section/desarrollo-section.component';
export { MerchanSectionComponent } from './merchan-section/merchan-section.component';
export { ContactoSectionComponent } from './contacto-section/contacto-section.component';
